include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    curly_braces_in_flow_control_structures: true
    empty_statements: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_null_checks: true