name: trainapp
description: Фитнес экосистема для тренеров и клиентов
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^10.0.0
  intl: ^0.20.2
  image_picker: ^1.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  equatable: ^2.0.8
  uuid: ^4.0.0
  fl_chart: ^0.66.0
  table_calendar: ^3.0.9
  open_file: ^3.5.11
  shared_preferences: ^2.2.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/